# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The possible types of things that can exist.
# Note that bullets are not treated as bodies.
class BodyType(object):
    MINER = 0
    BUILDER = 1
    SOLDIER = 2
    SAGE = 3
    ARCHON = 4
    LABORATORY = 5
    WATCHTOWER = 6


# Actions that can be performed.
# Purely aesthetic; have no actual effect on simulation.
# (Although the simulation may want to track the 'parents' of
# particular robots.)
# Actions may have 'targets', which are the units on which
# the actions were performed.
class Action(object):
    # Target: ID of robot attacked
    ATTACK = 0
    # Target: ID of robot spawned
    SPAWN_UNIT = 1
    # Target: location mined, x + y * width
    MINE_LEAD = 2
    # Target: location mined, x + y * width
    MINE_GOLD = 3
    # Target: none
    TRANSMUTE = 4
    # Target: none
    TRANSFORM = 5
    # Target: ID of robot mutated
    MUTATE = 6
    # Target: ID of robot repaired
    REPAIR = 7
    # Target: change in health (can be negative)
    CHANGE_HEALTH = 8
    # When a PROTOTYPE building upgrades to TURRET
    # Target: none
    FULLY_REPAIRED = 9
    # Target: Sage location, x + y * width
    LOCAL_ABYSS = 10
    # Target: Sage location, x + y * width
    LOCAL_CHARGE = 11
    # Target: Sage location, x + y * width
    LOCAL_FURY = 12
    # Target: none
    ABYSS = 13
    # Target: none
    CHARGE = 14
    # Target: none
    FURY = 15
    # Target: 0 if 90 degrees clockwise, 1 if horizontal, 2 if vertical
    VORTEX = 16
    # Dies due to an uncaught exception.
    # Target: none
    DIE_EXCEPTION = 17


# Events
# An Event is a single step that needs to be processed.
# A saved game simply consists of a long list of Events.
# Events can be divided by either being sent separately (e.g. as separate
# websocket messages), or by being wrapped with a GameWrapper.
# A game consists of a series of matches; a match consists of a series of
# rounds, and is played on a single map. Each round is a single simulation
# step.
class Event(object):
    NONE = 0
    # There should only be one GameHeader, at the start of the stream.
    GameHeader = 1
    # There should be one MatchHeader at the start of each match.
    MatchHeader = 2
    # A single simulation step. A round may be skipped if
    # nothing happens during its time.
    Round = 3
    # There should be one MatchFooter at the end of each simulation step.
    MatchFooter = 4
    # There should only be one GameFooter, at the end of the stream.
    GameFooter = 5


# A vector in two-dimensional space. Discrete space, of course.
# Defaults to the 0 vector.
class Vec(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # Vec
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec
    def X(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vec
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateVec(builder, x, y):
    builder.Prep(4, 8)
    builder.PrependInt32(y)
    builder.PrependInt32(x)
    return builder.Offset()


# A table of vectors.
class VecTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VecTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVecTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VecTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VecTable
    def Xs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VecTable
    def XsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # VecTable
    def XsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VecTable
    def XsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # VecTable
    def Ys(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VecTable
    def YsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # VecTable
    def YsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VecTable
    def YsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def VecTableStart(builder):
    builder.StartObject(2)

def VecTableAddXs(builder, xs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(xs), 0)

def VecTableStartXsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def VecTableAddYs(builder, ys):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ys), 0)

def VecTableStartYsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def VecTableEnd(builder):
    return builder.EndObject()



# A table of RGB values.
class RGBTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RGBTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRGBTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RGBTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RGBTable
    def Red(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RGBTable
    def RedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RGBTable
    def RedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RGBTable
    def RedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RGBTable
    def Green(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RGBTable
    def GreenAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RGBTable
    def GreenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RGBTable
    def GreenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # RGBTable
    def Blue(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RGBTable
    def BlueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RGBTable
    def BlueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RGBTable
    def BlueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def RGBTableStart(builder):
    builder.StartObject(3)

def RGBTableAddRed(builder, red):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(red), 0)

def RGBTableStartRedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RGBTableAddGreen(builder, green):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(green), 0)

def RGBTableStartGreenVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RGBTableAddBlue(builder, blue):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(blue), 0)

def RGBTableStartBlueVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RGBTableEnd(builder):
    return builder.EndObject()



# A list of new bodies to be placed on the map.
class SpawnedBodyTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpawnedBodyTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpawnedBodyTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SpawnedBodyTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The numeric ID of the new bodies.
    # Will never be negative.
    # There will only be one body with a particular ID at a time.
    # So, there will never be two robots with the same ID, or a robot and
    # a building with the same ID.
    # SpawnedBodyTable
    def RobotIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SpawnedBodyTable
    def RobotIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # SpawnedBodyTable
    def RobotIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpawnedBodyTable
    def RobotIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The teams of the new bodies.
    # SpawnedBodyTable
    def TeamIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SpawnedBodyTable
    def TeamIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # SpawnedBodyTable
    def TeamIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpawnedBodyTable
    def TeamIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The types of the new bodies.
    # SpawnedBodyTable
    def Types(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SpawnedBodyTable
    def TypesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # SpawnedBodyTable
    def TypesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpawnedBodyTable
    def TypesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # The locations of the bodies.
    # SpawnedBodyTable
    def Locs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SpawnedBodyTableStart(builder):
    builder.StartObject(4)

def SpawnedBodyTableAddRobotIds(builder, robotIds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(robotIds), 0)

def SpawnedBodyTableStartRobotIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def SpawnedBodyTableAddTeamIds(builder, teamIds):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teamIds), 0)

def SpawnedBodyTableStartTeamIdsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SpawnedBodyTableAddTypes(builder, types):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(types), 0)

def SpawnedBodyTableStartTypesVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def SpawnedBodyTableAddLocs(builder, locs):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(locs), 0)

def SpawnedBodyTableEnd(builder):
    return builder.EndObject()



# The map a round is played on.
class GameMap(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameMap()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameMap(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameMap
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The name of a map.
    # GameMap
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The bottom corner of the map.
    # GameMap
    def MinCorner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The top corner of the map.
    # GameMap
    def MaxCorner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = Vec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The map symmetry: 0 for rotation, 1 for horizontal, 2 for vertical.
    # GameMap
    def Symmetry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # The bodies on the map.
    # GameMap
    def Bodies(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SpawnedBodyTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The random seed of the map.
    # GameMap
    def RandomSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # The rubble on the map.
    # GameMap
    def Rubble(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameMap
    def RubbleAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameMap
    def RubbleLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def RubbleIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # The lead on the map.
    # GameMap
    def Lead(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameMap
    def LeadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameMap
    def LeadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def LeadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # The anomalies scheduled: 0/1/2/3 abyss/charge/fury/vortex.
    # GameMap
    def Anomalies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameMap
    def AnomaliesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameMap
    def AnomaliesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def AnomaliesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # The rounds the anomalies are scheduled for.
    # GameMap
    def AnomalyRounds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameMap
    def AnomalyRoundsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameMap
    def AnomalyRoundsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameMap
    def AnomalyRoundsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def GameMapStart(builder):
    builder.StartObject(10)

def GameMapAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def GameMapAddMinCorner(builder, minCorner):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(minCorner), 0)

def GameMapAddMaxCorner(builder, maxCorner):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(maxCorner), 0)

def GameMapAddSymmetry(builder, symmetry):
    builder.PrependInt32Slot(3, symmetry, 0)

def GameMapAddBodies(builder, bodies):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bodies), 0)

def GameMapAddRandomSeed(builder, randomSeed):
    builder.PrependInt32Slot(5, randomSeed, 0)

def GameMapAddRubble(builder, rubble):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rubble), 0)

def GameMapStartRubbleVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameMapAddLead(builder, lead):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(lead), 0)

def GameMapStartLeadVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameMapAddAnomalies(builder, anomalies):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(anomalies), 0)

def GameMapStartAnomaliesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameMapAddAnomalyRounds(builder, anomalyRounds):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(anomalyRounds), 0)

def GameMapStartAnomalyRoundsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameMapEnd(builder):
    return builder.EndObject()



# Metadata about all bodies of a particular type.
class BodyTypeMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BodyTypeMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBodyTypeMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BodyTypeMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BodyTypeMetadata
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def BuildCostLead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def BuildCostGold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level2CostLead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level2CostGold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level3CostLead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level3CostGold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def ActionCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def MovementCooldown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Health(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level2Health(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level3Health(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Damage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level2Damage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def Level3Damage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def ActionRadiusSquared(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def VisionRadiusSquared(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BodyTypeMetadata
    def BytecodeLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BodyTypeMetadataStart(builder):
    builder.StartObject(18)

def BodyTypeMetadataAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def BodyTypeMetadataAddBuildCostLead(builder, buildCostLead):
    builder.PrependInt32Slot(1, buildCostLead, 0)

def BodyTypeMetadataAddBuildCostGold(builder, buildCostGold):
    builder.PrependInt32Slot(2, buildCostGold, 0)

def BodyTypeMetadataAddLevel2CostLead(builder, level2CostLead):
    builder.PrependInt32Slot(3, level2CostLead, 0)

def BodyTypeMetadataAddLevel2CostGold(builder, level2CostGold):
    builder.PrependInt32Slot(4, level2CostGold, 0)

def BodyTypeMetadataAddLevel3CostLead(builder, level3CostLead):
    builder.PrependInt32Slot(5, level3CostLead, 0)

def BodyTypeMetadataAddLevel3CostGold(builder, level3CostGold):
    builder.PrependInt32Slot(6, level3CostGold, 0)

def BodyTypeMetadataAddActionCooldown(builder, actionCooldown):
    builder.PrependInt32Slot(7, actionCooldown, 0)

def BodyTypeMetadataAddMovementCooldown(builder, movementCooldown):
    builder.PrependInt32Slot(8, movementCooldown, 0)

def BodyTypeMetadataAddHealth(builder, health):
    builder.PrependInt32Slot(9, health, 0)

def BodyTypeMetadataAddLevel2Health(builder, level2Health):
    builder.PrependInt32Slot(10, level2Health, 0)

def BodyTypeMetadataAddLevel3Health(builder, level3Health):
    builder.PrependInt32Slot(11, level3Health, 0)

def BodyTypeMetadataAddDamage(builder, damage):
    builder.PrependInt32Slot(12, damage, 0)

def BodyTypeMetadataAddLevel2Damage(builder, level2Damage):
    builder.PrependInt32Slot(13, level2Damage, 0)

def BodyTypeMetadataAddLevel3Damage(builder, level3Damage):
    builder.PrependInt32Slot(14, level3Damage, 0)

def BodyTypeMetadataAddActionRadiusSquared(builder, actionRadiusSquared):
    builder.PrependInt32Slot(15, actionRadiusSquared, 0)

def BodyTypeMetadataAddVisionRadiusSquared(builder, visionRadiusSquared):
    builder.PrependInt32Slot(16, visionRadiusSquared, 0)

def BodyTypeMetadataAddBytecodeLimit(builder, bytecodeLimit):
    builder.PrependInt32Slot(17, bytecodeLimit, 0)

def BodyTypeMetadataEnd(builder):
    return builder.EndObject()



# Data relevant to a particular team.
class TeamData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TeamData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTeamData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TeamData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The name of the team.
    # TeamData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The java package the team uses.
    # TeamData
    def PackageName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The ID of the team this data pertains to.
    # TeamData
    def TeamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TeamDataStart(builder):
    builder.StartObject(3)

def TeamDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def TeamDataAddPackageName(builder, packageName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(packageName), 0)

def TeamDataAddTeamId(builder, teamId):
    builder.PrependInt8Slot(2, teamId, 0)

def TeamDataEnd(builder):
    return builder.EndObject()



# These tables are set-up so that they match closely with speedscope's file format documented at
# https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources.
# The client uses speedscope to show the recorded data in an interactive interface.
# A single event in a profile. Represents either an open event (meaning a
# method has been entered) or a close event (meaning the method was exited).
class ProfilerEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProfilerEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProfilerEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProfilerEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Whether this is an open event (true) or a close event (false).
    # ProfilerEvent
    def IsOpen(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # The bytecode counter at the time the event occurred.
    # ProfilerEvent
    def At(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # The index of the method name in the ProfilerFile.frames array.
    # ProfilerEvent
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ProfilerEventStart(builder):
    builder.StartObject(3)

def ProfilerEventAddIsOpen(builder, isOpen):
    builder.PrependBoolSlot(0, isOpen, 0)

def ProfilerEventAddAt(builder, at):
    builder.PrependInt32Slot(1, at, 0)

def ProfilerEventAddFrame(builder, frame):
    builder.PrependInt32Slot(2, frame, 0)

def ProfilerEventEnd(builder):
    return builder.EndObject()



# A profile contains all events and is labeled with a name.
class ProfilerProfile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProfilerProfile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProfilerProfile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProfilerProfile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The display-friendly name of the profile.
    # ProfilerProfile
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The events that occurred in the profile.
    # ProfilerProfile
    def Events(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ProfilerEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProfilerProfile
    def EventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProfilerProfile
    def EventsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ProfilerProfileStart(builder):
    builder.StartObject(2)

def ProfilerProfileAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def ProfilerProfileAddEvents(builder, events):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(events), 0)

def ProfilerProfileStartEventsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ProfilerProfileEnd(builder):
    return builder.EndObject()



# A profiler file is a collection of profiles.
# When profiling is enabled there is one of these per team per match.
class ProfilerFile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProfilerFile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProfilerFile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProfilerFile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The method names that are referred to in the events.
    # ProfilerFile
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ProfilerFile
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProfilerFile
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The recorded profiles, one per robot.
    # ProfilerFile
    def Profiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ProfilerProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ProfilerFile
    def ProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ProfilerFile
    def ProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ProfilerFileStart(builder):
    builder.StartObject(2)

def ProfilerFileAddFrames(builder, frames):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)

def ProfilerFileStartFramesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ProfilerFileAddProfiles(builder, profiles):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(profiles), 0)

def ProfilerFileStartProfilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def ProfilerFileEnd(builder):
    return builder.EndObject()



class Constants(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Constants()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConstants(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Constants
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Constants
    def IncreasePeriod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Constants
    def LeadAdditiveIncease(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ConstantsStart(builder):
    builder.StartObject(2)

def ConstantsAddIncreasePeriod(builder, increasePeriod):
    builder.PrependInt32Slot(0, increasePeriod, 0)

def ConstantsAddLeadAdditiveIncease(builder, leadAdditiveIncease):
    builder.PrependInt32Slot(1, leadAdditiveIncease, 0)

def ConstantsEnd(builder):
    return builder.EndObject()



# The first event sent in the game. Contains all metadata about the game.
class GameHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The version of the spec this game complies with.
    # GameHeader
    def SpecVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The teams participating in the game.
    # GameHeader
    def Teams(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = TeamData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def TeamsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def TeamsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Information about all body types in the game.
    # GameHeader
    def BodyTypeMetadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BodyTypeMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameHeader
    def BodyTypeMetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameHeader
    def BodyTypeMetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GameHeader
    def Constants(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Constants()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GameHeaderStart(builder):
    builder.StartObject(4)

def GameHeaderAddSpecVersion(builder, specVersion):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(specVersion), 0)

def GameHeaderAddTeams(builder, teams):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teams), 0)

def GameHeaderStartTeamsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameHeaderAddBodyTypeMetadata(builder, bodyTypeMetadata):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bodyTypeMetadata), 0)

def GameHeaderStartBodyTypeMetadataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameHeaderAddConstants(builder, constants):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(constants), 0)

def GameHeaderEnd(builder):
    return builder.EndObject()



# The final event sent in the game.
class GameFooter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameFooter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameFooter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameFooter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The ID of the winning team of the game.
    # GameFooter
    def Winner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def GameFooterStart(builder):
    builder.StartObject(1)

def GameFooterAddWinner(builder, winner):
    builder.PrependInt8Slot(0, winner, 0)

def GameFooterEnd(builder):
    return builder.EndObject()



# Sent to start a match.
class MatchHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatchHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMatchHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MatchHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The map the match was played on.
    # MatchHeader
    def Map(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = GameMap()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The maximum number of rounds in this match.
    # MatchHeader
    def MaxRounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MatchHeaderStart(builder):
    builder.StartObject(2)

def MatchHeaderAddMap(builder, map):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(map), 0)

def MatchHeaderAddMaxRounds(builder, maxRounds):
    builder.PrependInt32Slot(1, maxRounds, 0)

def MatchHeaderEnd(builder):
    return builder.EndObject()



# Sent to end a match.
class MatchFooter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatchFooter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMatchFooter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MatchFooter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The ID of the winning team.
    # MatchFooter
    def Winner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # The number of rounds played.
    # MatchFooter
    def TotalRounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Profiler data for team A and B if profiling is enabled.
    # MatchFooter
    def ProfilerFiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ProfilerFile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MatchFooter
    def ProfilerFilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MatchFooter
    def ProfilerFilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def MatchFooterStart(builder):
    builder.StartObject(3)

def MatchFooterAddWinner(builder, winner):
    builder.PrependInt8Slot(0, winner, 0)

def MatchFooterAddTotalRounds(builder, totalRounds):
    builder.PrependInt32Slot(1, totalRounds, 0)

def MatchFooterAddProfilerFiles(builder, profilerFiles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(profilerFiles), 0)

def MatchFooterStartProfilerFilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def MatchFooterEnd(builder):
    return builder.EndObject()



# A single time-step in a Game.
# The bulk of the data in the file is stored in tables like this.
# Note that a struct-of-arrays format is more space efficient than an array-
# of-structs.
class Round(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Round()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRound(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Round
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The IDs of teams in the Game.
    # Round
    def TeamIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def TeamIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def TeamIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TeamIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The total amount of lead change of this team, this round
    # Round
    def TeamLeadChanges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def TeamLeadChangesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def TeamLeadChangesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TeamLeadChangesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The total amount of gold change of this team, this round
    # Round
    def TeamGoldChanges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def TeamGoldChangesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def TeamGoldChangesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def TeamGoldChangesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # The IDs of bodies that moved.
    # Round
    def MovedIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def MovedIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def MovedIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def MovedIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # The new locations of bodies that have moved.
    # Round
    def MovedLocs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # New bodies.
    # Round
    def SpawnedBodies(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SpawnedBodyTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The IDs of bodies that died.
    # Round
    def DiedIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def DiedIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def DiedIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def DiedIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # The IDs of robots that performed actions.
    # IDs may repeat.
    # Round
    def ActionIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def ActionIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def ActionIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def ActionIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # The actions performed. These actions allow us to track how much soup or dirt a body carries.
    # Round
    def Actions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Round
    def ActionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Round
    def ActionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def ActionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # The 'targets' of the performed actions. Actions without targets may have any value
    # Round
    def ActionTargets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def ActionTargetsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def ActionTargetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def ActionTargetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # The locations of lead drops
    # Round
    def LeadDropLocations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The amount of lead dropped at each location
    # Round
    def LeadDropValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def LeadDropValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def LeadDropValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def LeadDropValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # The locations of gold drops
    # Round
    def GoldDropLocations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The amount of gold dropped at each location
    # Round
    def GoldDropValues(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def GoldDropValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def GoldDropValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def GoldDropValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # The IDs of the robots who changed their indicator strings
    # Round
    def IndicatorStringIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def IndicatorStringIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def IndicatorStringIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def IndicatorStringIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # The messages of the robots who changed their indicator strings
    # Round
    def IndicatorStrings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Round
    def IndicatorStringsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def IndicatorStringsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        return o == 0

    # The IDs of bodies that set indicator dots
    # Round
    def IndicatorDotIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def IndicatorDotIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def IndicatorDotIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def IndicatorDotIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        return o == 0

    # The location of the indicator dots
    # Round
    def IndicatorDotLocs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The RGB values of the indicator dots
    # Round
    def IndicatorDotRgbs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RGBTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The IDs of bodies that set indicator lines
    # Round
    def IndicatorLineIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def IndicatorLineIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def IndicatorLineIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def IndicatorLineIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # The start location of the indicator lines
    # Round
    def IndicatorLineStartLocs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The end location of the indicator lines
    # Round
    def IndicatorLineEndLocs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = VecTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The RGB values of the indicator lines
    # Round
    def IndicatorLineRgbs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RGBTable()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The first sent Round in a match should have index 1. (The starting state,
    # created by the MatchHeader, can be thought to have index 0.)
    # It should increase by one for each following round.
    # Round
    def RoundId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # The IDs of player bodies.
    # Round
    def BytecodeIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def BytecodeIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def BytecodeIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def BytecodeIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # The bytecodes used by the player bodies.
    # Round
    def BytecodesUsed(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Round
    def BytecodesUsedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Round
    def BytecodesUsedLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Round
    def BytecodesUsedIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

def RoundStart(builder):
    builder.StartObject(26)

def RoundAddTeamIds(builder, teamIds):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(teamIds), 0)

def RoundStartTeamIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddTeamLeadChanges(builder, teamLeadChanges):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(teamLeadChanges), 0)

def RoundStartTeamLeadChangesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddTeamGoldChanges(builder, teamGoldChanges):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(teamGoldChanges), 0)

def RoundStartTeamGoldChangesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddMovedIds(builder, movedIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(movedIds), 0)

def RoundStartMovedIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddMovedLocs(builder, movedLocs):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(movedLocs), 0)

def RoundAddSpawnedBodies(builder, spawnedBodies):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(spawnedBodies), 0)

def RoundAddDiedIds(builder, diedIds):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(diedIds), 0)

def RoundStartDiedIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddActionIds(builder, actionIds):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(actionIds), 0)

def RoundStartActionIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddActions(builder, actions):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(actions), 0)

def RoundStartActionsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def RoundAddActionTargets(builder, actionTargets):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(actionTargets), 0)

def RoundStartActionTargetsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddLeadDropLocations(builder, leadDropLocations):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(leadDropLocations), 0)

def RoundAddLeadDropValues(builder, leadDropValues):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(leadDropValues), 0)

def RoundStartLeadDropValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddGoldDropLocations(builder, goldDropLocations):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(goldDropLocations), 0)

def RoundAddGoldDropValues(builder, goldDropValues):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(goldDropValues), 0)

def RoundStartGoldDropValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddIndicatorStringIds(builder, indicatorStringIds):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorStringIds), 0)

def RoundStartIndicatorStringIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddIndicatorStrings(builder, indicatorStrings):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorStrings), 0)

def RoundStartIndicatorStringsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddIndicatorDotIds(builder, indicatorDotIds):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorDotIds), 0)

def RoundStartIndicatorDotIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddIndicatorDotLocs(builder, indicatorDotLocs):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorDotLocs), 0)

def RoundAddIndicatorDotRgbs(builder, indicatorDotRgbs):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorDotRgbs), 0)

def RoundAddIndicatorLineIds(builder, indicatorLineIds):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorLineIds), 0)

def RoundStartIndicatorLineIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddIndicatorLineStartLocs(builder, indicatorLineStartLocs):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorLineStartLocs), 0)

def RoundAddIndicatorLineEndLocs(builder, indicatorLineEndLocs):
    builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorLineEndLocs), 0)

def RoundAddIndicatorLineRgbs(builder, indicatorLineRgbs):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(indicatorLineRgbs), 0)

def RoundAddRoundId(builder, roundId):
    builder.PrependInt32Slot(23, roundId, 0)

def RoundAddBytecodeIds(builder, bytecodeIds):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(bytecodeIds), 0)

def RoundStartBytecodeIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundAddBytecodesUsed(builder, bytecodesUsed):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(bytecodesUsed), 0)

def RoundStartBytecodesUsedVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def RoundEnd(builder):
    return builder.EndObject()



# Necessary due to flatbuffers requiring unions to be wrapped in tables.
class EventWrapper(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventWrapper()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventWrapper(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventWrapper
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventWrapper
    def EType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EventWrapper
    def E(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EventWrapperStart(builder):
    builder.StartObject(2)

def EventWrapperAddEType(builder, eType):
    builder.PrependUint8Slot(0, eType, 0)

def EventWrapperAddE(builder, e):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(e), 0)

def EventWrapperEnd(builder):
    return builder.EndObject()



# If events are not otherwise delimited, this wrapper structure
# allows a game to be stored in a single buffer.
# The first event will be a GameHeader; the last event will be a GameFooter.
# matchHeaders[0] is the index of the 0th match header in the event stream,
# corresponding to matchFooters[0]. These indices allow quick traversal of
# the file.
class GameWrapper(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameWrapper()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameWrapper(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameWrapper
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The series of events comprising the game.
    # GameWrapper
    def Events(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = EventWrapper()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GameWrapper
    def EventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameWrapper
    def EventsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The indices of the headers of the matches, in order.
    # GameWrapper
    def MatchHeaders(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameWrapper
    def MatchHeadersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameWrapper
    def MatchHeadersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameWrapper
    def MatchHeadersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The indices of the footers of the matches, in order.
    # GameWrapper
    def MatchFooters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GameWrapper
    def MatchFootersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GameWrapper
    def MatchFootersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GameWrapper
    def MatchFootersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def GameWrapperStart(builder):
    builder.StartObject(3)

def GameWrapperAddEvents(builder, events):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(events), 0)

def GameWrapperStartEventsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameWrapperAddMatchHeaders(builder, matchHeaders):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(matchHeaders), 0)

def GameWrapperStartMatchHeadersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameWrapperAddMatchFooters(builder, matchFooters):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(matchFooters), 0)

def GameWrapperStartMatchFootersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def GameWrapperEnd(builder):
    return builder.EndObject()



